// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUgEQVHqXduYrk8cISi9gb8WCNbq-B_8U',
    appId: '1:935916330992:web:00f715c9e1990ff6678735',
    messagingSenderId: '935916330992',
    projectId: 'govassist-84f30',
    authDomain: 'govassist-84f30.firebaseapp.com',
    storageBucket: 'govassist-84f30.firebasestorage.app',
    measurementId: 'G-K7LES3ML5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf0z5y-fPfExwidn2sIyX_LMP_O759rkg',
    appId: '1:935916330992:android:927f684344f26d06678735',
    messagingSenderId: '935916330992',
    projectId: 'govassist-84f30',
    storageBucket: 'govassist-84f30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2OxvTwx-5nZGxjQx0LnCo0xma4Pnkj9E',
    appId: '1:935916330992:ios:2835a6cc2b552d9e678735',
    messagingSenderId: '935916330992',
    projectId: 'govassist-84f30',
    storageBucket: 'govassist-84f30.firebasestorage.app',
    iosClientId: '935916330992-8lglv8pmgtv0mffhgtrrjpf8v3ugmobv.apps.googleusercontent.com',
    iosBundleId: 'com.example.governmentAssisntant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2OxvTwx-5nZGxjQx0LnCo0xma4Pnkj9E',
    appId: '1:935916330992:ios:2835a6cc2b552d9e678735',
    messagingSenderId: '935916330992',
    projectId: 'govassist-84f30',
    storageBucket: 'govassist-84f30.firebasestorage.app',
    iosClientId: '935916330992-8lglv8pmgtv0mffhgtrrjpf8v3ugmobv.apps.googleusercontent.com',
    iosBundleId: 'com.example.governmentAssisntant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUgEQVHqXduYrk8cISi9gb8WCNbq-B_8U',
    appId: '1:935916330992:web:d9f37e70e9e9471f678735',
    messagingSenderId: '935916330992',
    projectId: 'govassist-84f30',
    authDomain: 'govassist-84f30.firebaseapp.com',
    storageBucket: 'govassist-84f30.firebasestorage.app',
    measurementId: 'G-LVKYC6N8CS',
  );

}